---
- name: "Load OS-specific variables for {{ ansible_os_family }}"
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: "Install Asterisk ({{ ansible_os_family }} specific)"
  ansible.builtin.include_tasks: "install_{{ ansible_os_family }}.yml"

- name: "Configure Asterisk and Deploy Audio"
  ansible.builtin.include_tasks: configure.yml