---
asterisk_service: asterisk
asterisk_user: asterisk
asterisk_group: asterisk
asterisk_conf_dir: /etc/asterisk
asterisk_module_dir: /usr/lib/asterisk/modules
asterisk_data_dir: /var/lib/asterisk
asterisk_cache_dir: /var/cache/asterisk
asterisk_sounds_dir: /usr/share/asterisk/sounds/en

asterisk_packages:
  - asterisk
  - asterisk-dev
  - asterisk-modules
  - asterisk-core-sounds-en
  - curl

system_dependencies:
  - build-essential
  - git
  - uuid-dev
  - libxml2-dev