[commons]
asterisk_pass = "SuperSecretPass"
asterisk_ami_secret = "SuperSecretPass"

[caller_sms]
twilio_account_sid = "SuperSecretAccountSID"
twilio_auth_token = "SuperSecretPass"

[database]
db_password = 'SuperSecretPass'

[py_phone_caller_ui]
ui_secret_key = "SuperSecretKey"
